### ISSUE TITLE
JPEGView freezes when moving zoomed image

### ISSUE THREAD

**Issue by IPeluchito** [annh9b/JPEGView-Static#10]
1. Open image with JPEGView.
2. Enlarge image with mouse wheel.
3. Move the enlarged image with the mouse.
4. JPEGview freezes.

Windows 11 build 22000.1516
GTX 1660Ti - 3840x2160 - 300% scaling

**Comment by annh9b** [comment]
Check it in the just released latest version - I can't reproduce.
