### ISSUE TITLE
Keymapping not working

### ISSUE THREAD

**Issue by IPeluchito** [annh9b/JPEGView-Static#12]
In previous versions there was a symbols.km file which had to be present for the key mapping to work... but in this latest version I see that this file does not exist and therefore the key mapping does not work....

**Comment by annh9b** [comment]
Thank you, it will be fixed in the next release. As for right now, you can download the file being discussed here:

[symbols.km](https://github.com/annh9b/JPEGView-Static/jpegview-static-post2024-vs2019-x64/src/JPEGView/Config/symbols.km)

**Comment by annh9b** [comment]
Fixed. Installer has been rebuilt.
