### ISSUE TITLE
Malware?

### ISSUE THREAD

**Issue by hotwareboy** [annh9b/JPEGView-Static#13]
Check your program.  It's installing a Trojan -  "Trojan:Win32/Commandrob.A!ml"

**Comment by annh9b** [comment]
No. This is open source software.

There are 2/73 false positives at VirusTotal:
https://www.virustotal.com/gui/file/5c66005773c26cf175b2400bfd08ddf96730c8fd5224d9f4e9303277903f9aa4/community
