### ISSUE TITLE
Where's all the readme from the original?

### ISSUE THREAD

**Issue by sylikc** [annh9b/JPEGView-Static#4]
Hi, I noticed this is a fork but with all of the readme details removed.

Also, www.open-source.tech seems to require GPLv3, but the original developer put it as GPLv2.

**Comment by rnldmssn** [comment]
I suppose she will adjust that...

**Comment by annh9b** [comment]
All original readme files are [here](https://github.com/annh9b/JPEGView-Static/tree/main/jpegview-static-post2024-vs2019-x64/src/JPEGView/Config/).
